name: Deployment pipeline
on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

concurrency: 
  group: "infisical-core-deployment"
  cancel-in-progress: true  

jobs:
  infisical-image:
    name: Build
    runs-on: ubuntu-latest
    environment: 
      name: infisical-build-stage
    outputs:
      image_tag: ${{ steps.commit.outputs.short }}  # Define the output at the job level
    steps:
    - uses: Infisical/secrets-action@v1.0.9
      with:
        method: "oidc"
        identity-id: "879be178-7f68-4405-ac2a-8ca273056f73"
        env-slug: "dev"
        project-slug: "hello-5m-vu"